import type {
  CameraMotion,
  ModelCapabilities,
  VideoAspectRatio,
  VideoDuration,
  VideoModel,
  VideoStylePreset,
} from '../types/video';

// ─── Capability presets ───────────────────────────────────────────────────────

const NO_REFS: ModelCapabilities = {
  maxReferenceImages: 0,
  supportsMultiReference: false,
  referenceMode: 'none',
  supportsCharacterReference: false,
  supportsLocationReference: false,
  supportsPropReference: false,
};

const SINGLE_CHARACTER: ModelCapabilities = {
  maxReferenceImages: 1,
  supportsMultiReference: false,
  referenceMode: 'single_image',
  supportsCharacterReference: true,
  supportsLocationReference: false,
  supportsPropReference: false,
};

const SINGLE_IMAGE: ModelCapabilities = {
  maxReferenceImages: 1,
  supportsMultiReference: false,
  referenceMode: 'single_image',
  supportsCharacterReference: false,
  supportsLocationReference: false,
  supportsPropReference: false,
};

/** Seedance 2.0: up to 9 images via image_urls[] */
const SEEDANCE_MULTI: ModelCapabilities = {
  maxReferenceImages: 9,
  supportsMultiReference: true,
  referenceMode: 'image_urls',
  supportsCharacterReference: true,
  supportsLocationReference: true,
  supportsPropReference: true,
};

// ─── Model registry ───────────────────────────────────────────────────────────

export const videoModels: VideoModel[] = [

  // ── Seedance ─────────────────────────────────────────────────────────────────
  {
    id: 'seedance-2',
    name: 'Seedance 2.0',
    provider: 'seedance',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsReferenceVideo: true,
    supportsAudio: true,
    maxDuration: 15,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: SEEDANCE_MULTI,
    estimatedCostLabel: 'Нужен баланс на seedance2.app',
    description: 'Seedance 2.0 — до 9 reference images, character + location + prop',
  },

  // ── Replicate ─────────────────────────────────────────────────────────────────
  {
    id: 'replicate-wan-t2v',
    name: 'Wan 2.1 T2V',
    provider: 'replicate',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: false,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 10,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: NO_REFS,
    estimatedCostLabel: 'Нужен баланс на Replicate',
    description: 'Wan 2.1 T2V — только текст, нет reference images',
  },
  {
    id: 'replicate-wan-i2v',
    name: 'Wan 2.1 I2V',
    provider: 'replicate',
    status: 'coming_soon',
    supportsTextToVideo: false,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 10,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: SINGLE_CHARACTER,
    estimatedCostLabel: 'Нужен баланс на Replicate',
    description: 'Wan 2.1 I2V — 1 reference image (character priority)',
  },
  {
    id: 'replicate-kling',
    name: 'Kling 1.5',
    provider: 'replicate',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 10,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: SINGLE_CHARACTER,
    estimatedCostLabel: 'Нужен баланс на Replicate',
    description: 'Kling 1.5 — 1 reference image (character priority)',
  },
  {
    id: 'replicate-luma',
    name: 'Luma Ray',
    provider: 'replicate',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 5,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: SINGLE_CHARACTER,
    estimatedCostLabel: 'Нужен баланс на Replicate',
    description: 'Luma Ray — 1 reference image',
  },

  // ── WaveSpeed ─────────────────────────────────────────────────────────────────
  {
    id: 'wavespeed-wan',
    name: 'WaveSpeed Wan',
    provider: 'wavespeed',
    status: 'active',
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 5,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: SINGLE_CHARACTER,
    estimatedCostLabel: '~$0.01–0.05 / видео',
    description: 'WaveSpeed Wan 2.1/2.2 — 1 reference image',
  },

  // ── HuggingFace (disabled) ────────────────────────────────────────────────────
  {
    id: 'huggingface-cogvideox',
    name: 'CogVideoX',
    provider: 'huggingface',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: false,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 10,
    aspectRatios: ['16:9'],
    capabilities: NO_REFS,
    estimatedCostLabel: 'Нужен платный HF Endpoint',
    description: 'CogVideoX-5b — требует платного HF Endpoint',
  },
  {
    id: 'huggingface-opensora',
    name: 'Open-Sora',
    provider: 'huggingface',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: false,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 10,
    aspectRatios: ['9:16', '16:9'],
    capabilities: NO_REFS,
    estimatedCostLabel: 'Нужен платный HF Endpoint',
    description: 'Open-Sora — требует платного HF Endpoint',
  },

  // ── Leonardo ──────────────────────────────────────────────────────────────────
  {
    id: 'leonardo-motion',
    name: 'Leonardo Motion',
    provider: 'leonardo',
    status: 'active',
    supportsTextToVideo: false,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 5,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: SINGLE_IMAGE,
    estimatedCostLabel: '~150 токенов / видео',
    description: 'Leonardo AI Motion SVD — 1 image-to-video',
  },

  // ── JSON2Video ────────────────────────────────────────────────────────────────
  {
    id: 'json2video',
    name: 'JSON2Video (слайд-шоу)',
    provider: 'json2video',
    status: 'active',
    supportsTextToVideo: false,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 15,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: SINGLE_IMAGE,
    estimatedCostLabel: 'По тарифу',
    description: 'Шаблонное видео из фото + текст. Не AI-генерация.',
  },

  // ── FREE / Open-Source (HF — disabled) ───────────────────────────────────────
  {
    id: 'cogvideox-free',
    name: 'CogVideoX Free',
    provider: 'cogvideox',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 5,
    aspectRatios: ['16:9', '9:16', '1:1'],
    capabilities: SINGLE_CHARACTER,
    estimatedCostLabel: 'Бесплатно (HuggingFace)',
    description: 'CogVideoX-5b open-source',
  },
  {
    id: 'ltx-fast',
    name: 'LTX Fast',
    provider: 'ltx',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 5,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: SINGLE_CHARACTER,
    estimatedCostLabel: 'Бесплатно (HuggingFace)',
    description: 'LTX-Video — быстрая генерация',
  },
  {
    id: 'svd',
    name: 'Stable Video Diffusion',
    provider: 'svd',
    status: 'coming_soon',
    supportsTextToVideo: false,
    supportsImageToVideo: true,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 5,
    aspectRatios: ['16:9'],
    capabilities: SINGLE_IMAGE,
    estimatedCostLabel: 'Бесплатно (HuggingFace)',
    description: 'SVD XT — анимация изображения',
  },
  {
    id: 'opensora-prep',
    name: 'Open-Sora',
    provider: 'opensora',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: false,
    supportsReferenceVideo: false,
    supportsAudio: false,
    maxDuration: 5,
    aspectRatios: ['9:16', '16:9'],
    capabilities: NO_REFS,
    estimatedCostLabel: 'Self-hosted',
    description: 'Open-Sora — self-hosted GPU',
  },

  // ── Coming Soon ───────────────────────────────────────────────────────────────
  {
    id: 'veo',
    name: 'Veo',
    provider: 'veo',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsReferenceVideo: true,
    supportsAudio: true,
    maxDuration: 15,
    aspectRatios: ['9:16', '16:9'],
    capabilities: {
      maxReferenceImages: 3,
      supportsMultiReference: true,
      referenceMode: 'image_urls',
      supportsCharacterReference: true,
      supportsLocationReference: true,
      supportsPropReference: true,
    },
    estimatedCostLabel: 'Скоро',
    description: 'Google Veo — ожидается',
  },
  {
    id: 'sora',
    name: 'Sora',
    provider: 'sora',
    status: 'coming_soon',
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsReferenceVideo: true,
    supportsAudio: true,
    maxDuration: 15,
    aspectRatios: ['9:16', '16:9', '1:1'],
    capabilities: {
      maxReferenceImages: 3,
      supportsMultiReference: true,
      referenceMode: 'image_urls',
      supportsCharacterReference: true,
      supportsLocationReference: true,
      supportsPropReference: true,
    },
    estimatedCostLabel: 'Скоро',
    description: 'OpenAI Sora — ожидается',
  },
];

export const videoModes = [
  { id: 'text_to_video', label: 'Text to Video' },
  { id: 'image_to_video', label: 'Image to Video' },
  { id: 'reference_to_video', label: 'Reference to Video' },
] as const;

export const aspectRatios: VideoAspectRatio[] = ['9:16', '16:9', '1:1'];
export const durations: VideoDuration[] = [5, 10, 15];
export const stylePresets: VideoStylePreset[] = [
  'Cinematic', 'UGC', 'App Promo', 'AI Social Platform Ad',
  'School Viral Reel', 'Product Demo', 'Character Story',
];
export const cameraMotions: CameraMotion[] = ['Static', 'Zoom in', 'Dolly in', 'Handheld', 'Orbit', 'Pan'];
